---
- name: Get dotfiles repository
  git:
    repo: "git@github.com:rwxd/.dotfiles.git"
    dest: "{{ lookup('env','HOME') }}/.dotfiles"
    version: main
    update: false
    recursive: false

- name: Install stow
  ansible.builtin.package:
    name: stow
    state: present
  become: true

- name: Create bin directory
  file:
    path: "~/.local/bin/"
    state: directory

- name: Create coc extensions directory
  file:
    path: "~/.coc/extensions/"
    state: directory

- name: Create gpg directory
  file:
    path: "~/.gpg"
    state: directory

- name: Create k9s config directory
  file:
    path: "~/.config/k9s"
    state: directory
