---
- name: Install system-tools
  ansible.builtin.package:
    name:
      - vim
      - git
      - htop
      - jq
      - make
      - yq
    state: latest
  become: true

- name: Install pacman packages
  community.general.pacman:
    name:
      - dnsutils
    state: present
  become: true
  when: ansible_distribution in ["Archlinux"]

- name: Install apt packages
  apt:
    name:
      - dnsuilts
    cache_valid_time: 600
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]
