---
- name: Install flutter
  kewlfft.aur.aur:
    name: flutter
    state: present
    use: yay
  when: ansible_distribution in ["Archlinux"]

- name: Install flutter required packages
  ansible.builtin.package:
    name:
      - cmake
      - ninja
      - pkg-config
    state: present
  become: true
