---
- name: Install joplin
  kewlfft.aur.aur:
    name: "joplin"
    state: present
    use: yay
  when: ansible_distribution in ["Archlinux"]

- name: Install joplin-desktop
  kewlfft.aur.aur:
    name: "joplin-desktop"
    state: present
    use: yay
  when: ansible_distribution in ["Archlinux"]
