---
- name: Install podman
  ansible.builtin.package:
    name: podman
    state: present
  become: true

- name: Configure /etc/container/*.conf
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  loop: []
  become: true
