---
- name: Install flatpak
  ansible.builtin.package:
    name:
      - flatpak
    state: latest
  become: true

- name: Install Flatseal
  community.general.flatpak:
    name: Flatseal
    state: present
