---
- name: Install block
  when: update_containerlab
  block:
    - name: Get containerlab archive
      get_url:
        url: "https://github.com/srl-labs/containerlab/releases/download/{{ containerlab_version }}/containerlab_{{ containerlab_version | replace('v', '') }}_Linux_amd64.tar.gz"
        dest: /tmp/containerlab.tar.gz

    - name: Create containerlab temp dir
      ansible.builtin.file:
        path: /tmp/containerlab
        state: directory
        mode: 0700

    - name: Extract containerlab
      ansible.builtin.unarchive:
        src: /tmp/containerlab.tar.gz
        dest: /tmp/containerlab/
        remote_src: true

    - name: Copy binary to bin
      ansible.builtin.copy:
        src: /tmp/containerlab/containerlab
        dest: /usr/bin/containerlab
        remote_src: true
        mode: "0755"
      become: true
