---
- name: Install tor
  ansible.builtin.package:
    name: tor
    state: present
  become: true

- name: Install tor-browser
  kewlfft.aur.aur:
    name: tor-browser
    state: present
    use: yay
  when: ansible_distribution in ["Archlinux"]

- name: Enable tor service
  ansible.builtin.systemd:
    name: tor.service
    enabled: true
    state: started
  become: true
