---
- name: Apply dev-environment
  hosts: localhost
  tasks:
    - name: Get current user
      ansible.builtin.command: whoami
      changed_when: false become: false
      register: whoami

    - name: Set sub_uid_users
      ansible.builtin.set_fact:
        subid_users:
          - "{{ whoami.stdout }}"

    - name: Include roles
      include_role:
        name: "{{ item }}"
      with_items:
        - update
        - system-tools
        - aur
        - zsh
        - subuid_subguid
        - neovim
        - tmux
        - dotfiles
        - virtualenv
        - tldr
        - bat
        - go
        - terraform
        - kubectl
        - k9s
        - nmap
        - trivy
        - docker
        - helm
        - pwgen
        - git-crypt
        - hadolint
        - ultimate-plumber
        # - kind
