---
- name: Apply dev-environment
  hosts: localhost
  tasks:
    - name: Get current user
      ansible.builtin.command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: Set sub_uid_users
      ansible.builtin.set_fact:
        subid_users:
          - "{{ whoami.stdout }}"

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        - update
        - system-tools
        - flatpak
        # - containerlab
        - podman
        - bluez
        - blueman
        - subuid_subgid
        - pavucontrol
        - aur
        - wireguard
        - zsh
        - neovim
        - wl-clipboard
        - xclip
        - kitty
        - plantuml
        - hadolint
        - dunst
        - tmux
        - ultimate-plumber
        - sipcalc
        - dotfiles
        - virtualenv
        - protonvpn
        - brave-browser
        - wireshark
        - tldr
        # - kind
        - bat
        - go
        - terraform
        - kubectl
        - k9s
        - nmap
        - nvm
        # - trivy
        - docker
        - helm
        - i3
        - rofi
        - feh
        - anki
        - nextcloud-client
        - obsidian
        # - joplin
        - libreoffice
        - steam-manjaro
        - lutris
        - bitwarden
        - pass
        - spotify
        - kvm
        - discord
        - wally
        - pwgen
        - android-tools
        - flameshot
        - vlc
        - element
        - git-crypt
        - nix
        - hugo
        - appimagelauncher
        - firejail
        # - flutter
        - tor
        - bfg
        - todoist
        - youtube-dl
        - shfmt
        - shellcheck
        - cryptomator
        - rust
        - github-cli
        - glab
