---
- name: Install wireguard-tools
  ansible.builtin.package:
    name: wireguard-tools
    state: present
  become: true

- name: Create wireguard-configs directory
  file:
    path: "~/.wireguard-configs/"
    state: directory
    mode: 0770
  become: false

